export type PlanOperativen = {
  PlanMonth: string;
  Object: string;
  PlanVolOre: number | null;
  PlanMassOre: number | null;
  PlanVolOreKet: number | null;
  PlanmassOreKet: number | null;
  PlanOreDepoVol: number | null;
  PlanOreDepoMass: number | null;
  PlanOreFromDepoVol: number | null;
  PlanOreFromDepoMass: number | null;
  PlanIBRDepoVol: number | null;
  PlanIBRDepoMass: number | null;
  PlanIBRFROMDepoVol: number | null;
  PlanIBRFROMDepoMass: number | null;
  PlanVolWaste: number | null;
  PlanMassWaste: number | null;
  PlanTkm: number | null;
  PlanTkmTruckDay: number | null;
  userAdded: string | null;
  percent_ore_KET: number | null;
  Cu_t_KET: number | null;
  percent_ore: number | null;
  Cu_t: number | null;
  percent_oreFromDepo: number | null;
  Cu_t_FromDepo: number | null;
  Cu_t_IBRFromDepo: number | null;
  percent_IBRFromDepo: number | null;
  PlanVolOreMasiv: number | null;
  PlanMassOreMasiv: number | null;
  PlanVolOreProsip: number | null;
  PlanMassOreProsip: number | null;
  PlanVolWasteProsip: number | null;
  PlanMassWasteProsip: number | null;
  percent_oreMasiv: number | null;
  Cu_t_Masiv: number | null;
  percent_oreProsip: number | null;
  Cu_t_Prosip: number | null;
  percent_oreDepo: number | null;
  Cu_t_Depo: number | null;
};

export type CreatePlanOperativenInput = {
  PlanMonthDay: string;
  Object: string;
  PlanVolOre: number | null;
  PlanMassOre: number | null;
  PlanVolOreKet: number | null;
  PlanmassOreKet: number | null;
  PlanOreFromDepoVol: number | null;
  PlanOreFromDepoMass: number | null;
  PlanIBRDepoVol: number | null;
  PlanIBRDepoMass: number | null;
  PlanIBRFROMDepoVol: number | null;
  PlanIBRFROMDepoMass: number | null;
  PlanVolWaste: number | null;
  PlanMassWaste: number | null;
  PlanTkm: number | null;
  PlanTkmTruckDay: number | null;
  percent_ore_KET: number | null;
  Cu_t_KET: number | null;
  percent_ore: number | null;
  Cu_t: number | null;
  percent_oreFromDepo: number | null;
  Cu_t_FromDepo: number | null;
  Cu_t_IBRFromDepo: number | null;
  percent_IBRFromDepo: number | null;
  PlanVolOreMasiv: number | null;
  PlanMassOreMasiv: number | null;
  PlanVolOreProsip: number | null;
  PlanMassOreProsip: number | null;
  PlanOreDepoVol: number | null;
  PlanOreDepoMass: number | null;
  PlanVolWasteProsip: number | null;
  PlanMassWasteProsip: number | null;
  percent_oreMasiv: number | null;
  Cu_t_Masiv: number | null;
  percent_oreProsip: number | null;
  Cu_t_Prosip: number | null;
  percent_oreDepo: number | null;
  Cu_t_Depo: number | null;
  PlanVolIBRToDepo: number | null;
  PlanMassIBRToDepo: number | null;
  percent_IBRToDepo: number | null;
  Cu_t_IBRToDepo: number | null;
  userAdded: string | null;
};

