export type PlanNP = {
  PlanMonth: string;
  Object: string;
  PlanVolOre: number | null;
  PlanMassOre: number | null;
  percent_ore: number | null;
  Cu_t: number | null;
  PlanVolOreFromDepo: number | null;
  PlanMassOreFromDepo: number | null;
  percent_oreFromDepo: number | null;
  Cu_t_FromDepo: number | null;
  PlanVolIBRFromDepo: number | null;
  PlanMassIBRFromDepo: number | null;
  percent_IBRFromDepo: number | null;
  Cu_t_IBRFromDepo: number | null;
  PlanVolOreKet: number | null;
  PlanMassOreKet: number | null;
  percent_oreKet: number | null;
  Cu_t_Ket: number | null;
  PlanVolOreDepo: number | null;
  PlanMassOreDepo: number | null;
  percent_oreDepo: number | null;
  Cu_t_Depo: number | null;
  PlanVolIBRToDepo: number | null;
  PlanMassIBRToDepo: number | null;
  percent_IBRToDepo: number | null;
  Cu_t_IBRToDepo: number | null;
  PlanVolWaste: number | null;
  PlanMassWaste: number | null;
  PlanVolTot: number | null;
  PlanMassTot: number | null;
  Planvol: number | null;
  PlanMass: number | null;
  PlanTkmOre: number | null;
  AvgkmOre: number | null;
  PlanTkmWaste: number | null;
  AvgkmWaste: number | null;
  PlanTkm: number | null;
  Avgkm: number | null;
  userAdded: string | null;
};

export type CreatePlanNPInput = {
  PlanMonthDay: string;
  PlanType: string;
  Object: string;
  PlanVolOre: number | null;
  PlanMassOre: number | null;
  percent_ore: number | null;
  Cu_t: number | null;
  PlanVolOreKet: number | null;
  PlanMassOreKet: number | null;
  percent_oreKet: number | null;
  Cu_t_Ket: number | null;
  PlanVolOreFromDepo: number | null;
  PlanMassOreFromDepo: number | null;
  percent_oreFromDepo: number | null;
  Cu_t_FromDepo: number | null;
  PlanVolIBRFromDepo: number | null;
  PlanMassIBRFromDepo: number | null;
  percent_IBRFromDepo: number | null;
  Cu_t_IBRFromDepo: number | null;
  PlanVolOreDepo: number | null;
  PlanMassOreDepo: number | null;
  percent_oreDepo: number | null;
  Cu_t_Depo: number | null;
  PlanVolIBRToDepo: number | null;
  PlanMassIBRToDepo: number | null;
  percent_IBRToDepo: number | null;
  Cu_t_IBRToDepo: number | null;
  PlanVolWaste: number | null;
  PlanMassWaste: number | null;
  PlanVolTot: number | null;
  PlanMassTot: number | null;
  Planvol: number | null;
  PlanMass: number | null;
  PlanTkmOre: number | null;
  AvgkmOre: number | null;
  PlanTkmWaste: number | null;
  AvgkmWaste: number | null;
  PlanTkm: number | null;
  Avgkm: number | null;
  userAdded: string | null;
};


